name: Core
main: me.chickencoop.server.Core
version: 1.0
commands:
    freeze:
        description: Freezes the selected player. Deputy+
    tp:
        description: Teleports you to the selected player. Mod+
    tphere:
        description: Teleports the selected player to you. Mod+
    re:
        description: Reloads the server. Owner+
    vanish:
        description: Vanishes the sender. Mod+
    addgold:
        description: Gives 150 gold to the selected player. Admin+
    removegold:
        description: Takes 150 gold from the selected player. Admin+
    gmc:
        description: Sets your gamemode to creative. Admin+
    gms:
        description: Sets your gamemode to survival. Admin+
    gma:
        description: Sets your gamemode to adventure. Admin+
    op:
        description: Ops the selected player. Owner+
    deop:
        description: Deops the selected player. Owner+
    cc:
        description: Clears the global chat. Mod+
    fly:
        description: Allows the sender to fly. Mod+
    afk:
        description: Announces that the sender is afk. Member+